services:
  init-postgres:
    image: postgres:latest
    ports:
      - 4321:5432
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_DB_USR}
      POSTGRES_PASSWORD: ${PG_DB_PWD}
      JYOTISH_DB: ${JM_DB}
      JYOTISH_USER: ${JM_DB_USR}
      JYOTISH_PASSWORD: ${JM_DB_PWD}
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
      - type: bind
        source: ./script
        target: /docker-entrypoint-initdb.d
        read_only: true
